version: '3.8'

services:
  member-service:
    image: 009160040466.dkr.ecr.ap-northeast-2.amazonaws.com/learn-run/member-service:latest
    container_name: member-service
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - shared-net

networks:
  shared-net:
    external: true