version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_test
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/user/local/conf/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    command: redis-server /user/local/conf/redis.conf

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: learn_run_member
      MYSQL_USER: learn_run_user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: 009160040466.dkr.ecr.ap-northeast-2.amazonaws.com/learn-run/member-service:latest
    container_name: member-service
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: