spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/learn_run_member
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      idle-timeout: 300000
      max-lifetime: 900000
      connection-timeout: 10000

  kafka:
    bootstrap-servers: ${EC2_INFRA_HOST}:10000,${EC2_INFRA_HOST}:10001,${EC2_INFRA_HOST}:10002

  data:
    redis:
      host: ${EC2_INFRA_HOST}
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka